spring:
  application:
    name: cleancode

  datasource:
    url: 'jdbc:h2:tcp://localhost/~/cleancode'
    username: 'sa'
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  # SQL? ??
    properties:
      hibernate:
        format_sql: true  # SQL? ?? ?? ??

  # SQL ?? ??? ??? ?? (?? ??)
  logging:
    level:
      org.hibernate.SQL: DEBUG  # SQL ?? ?? ?? ??
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # ???? ????? ??? ??

  sql:
    init:
      mode: always  # SQL