### 1. 모든 강의 인스턴스 조회 (GET 요청)
GET http://localhost:8080/lectureInstances/getAllLectureInstances

### 2. ID 기반 강의 인스턴스 조회 (GET 요청)
GET http://localhost:8080/lectureInstances/1

### 3. ID 및 날짜 기반 강의 인스턴스 조회 (GET 요청)
GET http://localhost:8080/lectureInstances/1/date?date=2024-11-01

### 4. 강의 인스턴스 등록 (POST 요청)
POST http://localhost:8080/lectureInstances/add
Content-Type: application/json

{
  "id": 1,
  "startDate": "2024-11-01",
  "endDate": "2024-12-10",
  "maxParticipants": 30,
  "currentParticipants": 10,
  "status": "OPEN",
  "lectureDto": {
    "id": 1,
    "title": "Clean Architecture",
    "instructor": "허재"
  }
}

### 5. 강의 인스턴스 수정 (PUT 요청)
PUT http://localhost:8080/lectureInstances/update
Content-Type: application/json

{
  "id": 1,
  "startDate": "2024-11-01",
  "endDate": "2024-12-10",
  "maxParticipants": 30,
  "currentParticipants": 10,
  "status": "OPEN",
  "lectureDto": {
    "id": 1,
    "title": "Updated Clean Architecture",
    "instructor": "허재"
  }
}

### 6. 강의 인스턴스 삭제 (DELETE 요청)
DELETE http://localhost:8080/lectureInstances/delete/1
